#!/bin/sh
set -e

case "$1" in
  remove)
    ;;

  purge)
    rm -f /var/log/graylog2.*
    ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

  *)
    echo "$0 called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac
